### ISSUE TITLE
[providers/config] Is there an explicit credentials provider?

### ISSUE THREAD

**Issue by charlesg3** [techascent/tech.io#1]
I dug around the code briefly but figured you might be able to get this going quicker than I...

The widespread-english site was using vault, however the vault keys expire if they don't get renewed quick enough -- regardless we need a setup where we can provide perma-creds. Ideally I'd like to do this through the config whereby I simply provide `:aws-access-key-id` and `:aws-secret-access-key` and (optional) `:aws-session-token` (possibly "")... and if those are obtained from the config then I can provide them through the environment (e.g. during the deploy process) and the container / app won't have to worry about obtaining creds from the vault or renewing in order to upload files (which really needs to be robust on this site).

**Comment by cnuernber** [comment]
@charlesg3 :

Two Pathways:

### Env  Pathway

The aws provider chain should pick up the environment variables automatically.  So if you want to set permanent env vars and use the normal aws env names (which you have up above), no changes should be necessary.  I just tested this against techascent.test:

```clojure
;; no creds
 
user=> (require '[tech.io.s3 :as s3])
nil
user=> (s3/list-objects "techascent.test" "" {})

AmazonS3Exception The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: 19FC90445AE06817; S3 Extended Request ID: jXrHZnvfVtXDh2RTtyTU18XNtuLWyi1fX+P14yAa7PntYMlrCs+VSFUWgtxEF2z5mFtg+45WPmE=)  com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse (AmazonHttpClient.java:1695)

;; creds from
;; source ~/dev/widespread-english/core-access


user=> (require '[tech.io.s3 :as s3])
nil
user=> (s3/list-objects "techascent.test" "" {})
({:bucket-name "techascent.test", :key "prefix/", :directory? true} {:bucket-name "techascent.test", :etag "d946b9012ee27df5d3d194f555c7de0d", :storage-class "STANDARD", :last-modified #object[org.joda.time.DateTime 0x3f761121 "2018-12-21T10:03:10.000-07:00"], :key "test-key", :size 2} {:bucket-name "techascent.test", :etag "23794538a8d23a2af9cfc4aa646a4fc7", :storage-class "STANDARD", :last-modified #object[org.joda.time.DateTime 0x272e0584 "2018-12-23T14:41:52.000-07:00"], :key "test.edn", :size 6} {:bucket-name "techascent.test", :etag "a934dd45f2ce49d8c9c921c236c062ab", :storage-class "STANDARD", :last-modified #object[org.joda.time.DateTime 0x22f4d6cc "2018-12-21T10:03:10.000-07:00"], :key "testfile.txt", :size 8} {:bucket-name "techascent.test", :etag "d8e8fca2dc0f896fd7cb4cb0031ba249", :storage-class "STANDARD", :last-modified #object[org.joda.time.DateTime 0x2102b2c "2018-02-01T15:05:09.000-07:00"], :key "testfile2.txt", :size 5})
```

### IAM Pathway

Another pathway would be to make the machine part of an IAM group that has the creds required.  

Either of these pathways means the vault auth provider should be disabled in the app-config of wse:


#### Disable Vault Auth Provider

```clojure
{:tech-io-vault-auth false}
```

Then the system will use the aws provider chain and not attempt to provide creds.

**Comment by charlesg3** [comment]
Got it -- thanks. This can be closed.

**Comment by cnuernber** [comment]
Cool, if it doesn't work as expected by all means let's reopen this and I will get on it immediately.
