### ISSUE TITLE
Remove caching/redirect providers

### ISSUE THREAD

**Issue by cnuernber** [techascent/tech.io#3]
Authentication makes sense -it would be a large burden to refactor existing code to explicitly pass in authentication information as opposed to what it is now

No one, absolutely no one aside from us is ever going to use the caching or redirect providers.  They will just re-engineer some copy-local scheme and that will work fine for them.

Removing those two I think would simplify the library and focus it more as a launching point for url->data pathways where the url protocol dictates the underlying communication backend.

**Comment by cnuernber** [comment]
@harold, @charlesg3 - Need opinions here when you have time.  I want to remove the parts of this library that we aren't using.  The old s3 library always cached locally and I just at this point feel like that is better done as a layer on top as opposed to a layer inside.

**Comment by harold** [comment]
Sounds good to me. Deleted code is debugged code.

**Comment by cnuernber** [comment]
Fixed in 8742ec7574b41367a741a1e22d045155782ffc90
