### ISSUE TITLE
tech.v3.io.url/url? improper on windows file-paths, causing tech.v3.io/input-stream to throw

### ISSUE THREAD

**Issue by joinr** [techascent/tech.io#6]
Discovered while messing with tech.ml.dataset on windows, eventually traced down to tech.v3.io.url (default parser that tmd uses for submitting paths for csv/tsv files apparently):

https://github.com/techascent/tech.io/blob/master/src/tech/v3/io/url.clj#L70

given:

(def path "C:\\Users\\joinr\\data\\yellow_tripdata_2016-01.csv")

(.exists (clojure.java.io/file path)) ;;true

(tech.v3.io.url/url? path) ;;:C:\Users\joinr\data\yellow_tripdata_2016-01.cs

(tech.v3.io/input-stream path) 

Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2).
C:\Users\joinr\data\yellow_tripdata_2016-01.cs: (The filename, directory name, or volume label syntax is incorrect)

(tech.v3.io.url/url->parts path)
{:protocol :C:\Users\joinr\data\yellow_tripdata_2016-01.cs,  ;;invalid protocol, happens to chop off v as well.
 :path (),
 :arguments nil}

(tech.v3.io.url/url->parts "http://www.blah.com")  
{:protocol :http, :path ("www.blah.com"), :arguments nil} ;;as expected

(tech.v3.io.url/url->parts "c:\\i\\am\\not\\a\\url")
{:protocol :c:\i\am\not\a\ur, :path (), :arguments nil} ;;should throw per the existing semantics..

Proposed solution:

Instead of custom URL parsing in `url?`, try to construct a java.net.URL instance and see if it validly parses.

This patch enables native file paths to work on windows and should strengthen the url? predicate.

[patch.diff](https://github.com/techascent/tech.io/files/6240214/patch.diff.txt)

**Comment by harold** [comment]
@joinr - my man. Long time no see. Hope everything is cool in your world :sunglasses: 

This is great thinking about `url?`

A cursory search through our codebase shows that this function is basically internal to this lib, so hardening it is unlikely to unexpectedly break other consumers.

And I see where the check for `:` is assuming that means a protocol, where on windows `:` is quintessential as in your case of see colon backslash.

Check out the associated PR (https://github.com/techascent/tech.io/pull/7) and let me know what you think (@joinr @cnuernber)

**Comment by cnuernber** [comment]
Looks good.  No spec deps and added test.  Certainly better than it was.

**Comment by joinr** [comment]
@harold  Looks good to me; thanks :)
